version: "3.9"
services:
  sirha-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATA_MONGODB_URI: "${SPRING_DATA_MONGODB_URI}"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 5
      start_period: 40s